name=linguist
version=0.1.0
edition=pim4
entry=src/Main.mod
includes=src

[deps]
m2cli=path:/Users/mattfitz/dev/m2/libs/m2cli
m2path=path:/Users/mattfitz/dev/m2/libs/m2path
m2glob=path:/Users/mattfitz/dev/m2/libs/m2glob
m2text=path:/Users/mattfitz/dev/m2/libs/m2text
m2fmt=path:/Users/mattfitz/dev/m2/libs/m2fmt
m2hash=path:/Users/mattfitz/dev/m2/libs/m2hash
m2tok=path:/Users/mattfitz/dev/m2/libs/m2tok

[cc]
extra-c=src/bridge.c /Users/mattfitz/dev/m2/libs/m2sys/m2sys.c

[test]
entry=tests/TestMain.mod
